server:
  port: 8090
  address: 0.0.0.0
  servlet:
    context-path: /api
spring:
  application:
    name: qqbot
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
    port: 587
    username: 3805912450@qq.com
    password: rnfscwlzxwukcbfi
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.138.136.39:3306/qq_db?characterEncoding=utf-8&serverTimeZone=Asia/Shanghai
    username: root
    password: 1234567890
  data:
    redis:
      host: 8.138.136.39
      port: 6379
      password: 1234567890
      database: 0
      username: default
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      fail-on-empty-beans: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  security:
    jwt:
      key: ...-..---...-.-.-----..-
      expire: 86400000
      issuer: Astolfo
      jwt-algorithm: HS256
      jca-algorithm: HmacSHA256
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: true
      logic-not-delete-value: false
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.timeleafing.qqbot.domain.entity
minio:
  public-base-url: http://8.138.136.39:9000
  endpoint: http://8.138.136.39:9000
  access-key: timeleafing
  secret-key: 1234567890
  presigned-url-expiry: 3600
  part-size: 5242880
  default-bucket: default-bucket
okhttp:
  connect-timeout: 10
  read-timeout: 30
  write-timeout: 30
shiro:
  ws:
    server:
      enable: true
      url: "/ws/shiro"
qqbot:
  qq-bot-id: 3805912450
minecraft:
  ws-uri: ws://111.170.33.8:30123/api/minecraft/ws/log
  http-uri: http://111.170.33.8:30123/api/minecraft
hmac-security:
  hmac-secret: lIYMNDJ7iejvwPM/QbtIJ6/RMlefR3oU8OzEAt61oVhpyTwy0Wp/ajdZcHZMGG2L
  header-ts: X-TS
  header-nonce: X-NONCE
  header-sign: X-SIGN
  allowed-hosts: ["111.170.33.8"]